Repository webview/webview, pull requests merged in 2024-08, with the labels that each got.

#1114 Do not set an auto released delegate (macOS) (#1113)
  webview.h
Labels: bug

#1125 Add support for WebKitGTK API 6.0 and GTK 4
  .github/workflows/ci.yaml
  CHANGELOG.md
  README.md
  script/build.sh
  webview.h
Labels: enhancement, documentation, ci, scripts

#1129 Fix warnings
  examples/bind.c
  webview.h
Labels: enhancement, examples

#1132 Fix GTK info in readme
  README.md
Labels: documentation

#1133 Make macOS app bundles for examples
  examples/CMakeLists.txt
  examples/resources/macos/app_icon.icns
  examples/resources/macos/resources.cmake
  examples/resources/windows/resources.cmake
  examples/resources/windows/resources.rc
  examples/resources/windows/version.rc.in
  examples/resources/windows/webview.ico
Labels: examples
