Repository webview/webview, pull requests merged in 2024-02, with the labels that each got.

#1069 Fix JSON escaping with UTF-8
  webview.h
  webview_test.cc
Labels: bug

#1071 Fix webview_get_window documentation for Win32
  webview.h
Labels: documentation

#1072 Allow passing HWND to webview_create (Win32)
  webview.h
Labels: enhancement

#1073 Set focus to webview widget when owned window activates (Win32)
  webview.h
Labels: enhancement

#1074 Embed WebView2 into a child window (Win32)
  webview.h
Labels: enhancement

#1064 Expose native handles to web views
  webview.h
  webview.i
Labels: enhancement

#1076 Reduce interference with user-owned window (Win32)
  webview.h
Labels: enhancement

#1077 Prevent unintentionally posting quit message multiple times (Win32)
  webview.h
Labels: enhancement

#1078 Fix WKWebViewConfiguration leak (macOS)
  webview.h
Labels: bug

#1079 Remove unused variable (Win32)
  webview.h
Labels: enhancement

#1080 Delete webview copy/move constructor/assignment
  webview.h
Labels: enhancement

#1081 Fix move support in native_library and com_init_wrapper
  webview.h
Labels: bug

#1083 Update GHA actions
  .github/workflows/ci.yaml
Labels: ci

#1084 Change webview class hierarchy
  webview.h
Labels: enhancement

#1085 Last window closed custom logic (macOS)
  webview.h
Labels: enhancement

#1086 Fixes for destruct behavior/cleanup
  webview.h
Labels: bug

#1087 Fix various memory management issues (macOS)
  webview.h
Labels: bug

#1088 Initial work on documentation generation with Doxygen
  .github/workflows/ci.yaml
  Doxyfile
  webview.h
Labels: documentation

#1089 Change size hints from #define to an enum
  webview.h
  webview_test.cc
Labels: enhancement

#1090 Fix warnings
  .clang-tidy
  examples/bind.c
  script/build.sh
  webview.h
Labels: enhancement, scripts

#1093 Link dl library (Linux/macOS)
  script/build.sh
Labels: bug

#1097 Rework RPC code and examples
  .clang-tidy
  examples/bind.c
  examples/bind.cc
  webview.h
  webview_test.cc
Labels: bug, enhancement, examples

#1099 Rework error handling and reporting
  examples/basic.cc
  examples/bind.cc
  webview.h
  webview_test.cc
Labels: enhancement

#1100 Default-construct basic_result<T, ...> with value
  webview.h
  webview_test.cc
Labels: enhancement
