Repository webview/webview, pull requests merged in 2024-09, with the labels that each got.

#1135 Use cxx_std_11 compile feature
  cmake/internal.cmake
  core/CMakeLists.txt
Labels: scripts

#1138 added inline to get_file_version_string and cast_to_webview
  core/include/webview/webview.h
Labels: bug

#1141 Update APT to fix "Failed to fetch mirror" in CI
  .github/workflows/check.yaml
  .github/workflows/ci.yaml
  .github/workflows/setup-env/action.yaml
Labels: ci

#350 Fixed set_size in cocoa to keep same window position when changing size
  core/include/webview/detail/backends/cocoa_webkit.hh
  core/include/webview/detail/platform/darwin/objc.hh
Labels: type: fix, os: macos

#1194 Fix #1192: CMake GTK detection logic leading to incorrect builds
  cmake/webview.cmake
Labels: scope: build, type: fix, os: linux

#1193 Fix Web Inspector layout (macOS)
  core/include/webview/detail/backends/cocoa_webkit.hh
  core/include/webview/detail/platform/darwin/cocoa.hh
Labels: type: fix, os: macos

#1196 Runtime compatibility with old macOS
  core/include/webview/detail/backends/cocoa_webkit.hh
  core/include/webview/detail/engine_base.hh
Labels: type: improvement, os: macos

#1197 Make EventToken.h compatible with C compilers
  compatibility/mingw/include/EventToken.h
Labels: type: improvement, os: windows

#1201 Add missing package-dev column to build matrix
  .github/workflows/build_matrix.csv
  .github/workflows/build_matrix_schema.json
Labels: scope: build, type: fix

#1202 Fix amalgamation script failing on Windows
  .github/workflows/ci.yaml
  README.md
  scripts/amalgamate.py
Labels: scope: build, type: fix, os: windows
