Repository webview/webview, pull requests merged in 2025-04, with the labels that each got.

#1277 macOS Objective-C refactor
  core/include/webview/detail/backends/cocoa_webkit.hh
  core/include/webview/detail/platform/darwin/cocoa/NSApplication.hh
  core/include/webview/detail/platform/darwin/cocoa/NSBundle.hh
  core/include/webview/detail/platform/darwin/cocoa/NSEvent.hh
  core/include/webview/detail/platform/darwin/cocoa/NSInvocation.hh
  core/include/webview/detail/platform/darwin/cocoa/NSMethodSignature.hh
  core/include/webview/detail/platform/darwin/cocoa/NSNotification.hh
  core/include/webview/detail/platform/darwin/cocoa/NSNumber.hh
  core/include/webview/detail/platform/darwin/cocoa/NSObject.hh
  core/include/webview/detail/platform/darwin/cocoa/NSOpenPanel.hh
  core/include/webview/detail/platform/darwin/cocoa/NSPoint.hh
  core/include/webview/detail/platform/darwin/cocoa/NSRect.hh
  core/include/webview/detail/platform/darwin/cocoa/NSSavePanel.hh
  core/include/webview/detail/platform/darwin/cocoa/NSSize.hh
  core/include/webview/detail/platform/darwin/cocoa/NSString.hh
  core/include/webview/detail/platform/darwin/cocoa/NSURL.hh
  core/include/webview/detail/platform/darwin/cocoa/NSURLRequest.hh
  core/include/webview/detail/platform/darwin/cocoa/NSView.hh
  core/include/webview/detail/platform/darwin/cocoa/NSWindow.hh
  core/include/webview/detail/platform/darwin/cocoa/cocoa.hh
  core/include/webview/detail/platform/darwin/cocoa/literals.hh
  core/include/webview/detail/platform/darwin/cocoa/types.hh
  core/include/webview/detail/platform/darwin/objc/Class.hh
  core/include/webview/detail/platform/darwin/objc/autoreleasepool.hh
  core/include/webview/detail/platform/darwin/objc/invoke.hh
  core/include/webview/detail/platform/darwin/objc/literals.hh
  core/include/webview/detail/platform/darwin/objc/memory.hh
  core/include/webview/detail/platform/darwin/objc/objc.hh
  core/include/webview/detail/platform/darwin/webkit/WKOpenPanelParameters.hh
  core/include/webview/detail/platform/darwin/webkit/WKScriptMessage.hh
  core/include/webview/detail/platform/darwin/webkit/WKUserContentController.hh
  core/include/webview/detail/platform/darwin/webkit/WKUserScript.hh
  core/include/webview/detail/platform/darwin/webkit/WKWebView.hh
  core/include/webview/detail/platform/darwin/webkit/WKWebViewConfiguration.hh
  core/include/webview/detail/platform/darwin/webkit/literals.hh
  core/include/webview/detail/platform/darwin/webkit/webkit.hh
Labels: type: refactor, os: macos

#1284 Use void return type internally in objc::release()
  core/include/webview/detail/platform/darwin/objc/memory.hh
Labels: type: fix, os: macos

#1285 Remove user-defined literal operators
  core/include/webview/detail/backends/cocoa_webkit.hh
  core/include/webview/detail/platform/darwin/cocoa/NSApplication.hh
  core/include/webview/detail/platform/darwin/cocoa/NSBundle.hh
  core/include/webview/detail/platform/darwin/cocoa/NSEvent.hh
  core/include/webview/detail/platform/darwin/cocoa/NSInvocation.hh
  core/include/webview/detail/platform/darwin/cocoa/NSMethodSignature.hh
  core/include/webview/detail/platform/darwin/cocoa/NSNotification.hh
  core/include/webview/detail/platform/darwin/cocoa/NSNumber.hh
  core/include/webview/detail/platform/darwin/cocoa/NSObject.hh
  core/include/webview/detail/platform/darwin/cocoa/NSOpenPanel.hh
  core/include/webview/detail/platform/darwin/cocoa/NSSavePanel.hh
  core/include/webview/detail/platform/darwin/cocoa/NSString.hh
  core/include/webview/detail/platform/darwin/cocoa/NSURL.hh
  core/include/webview/detail/platform/darwin/cocoa/NSURLRequest.hh
  core/include/webview/detail/platform/darwin/cocoa/NSView.hh
  core/include/webview/detail/platform/darwin/cocoa/NSWindow.hh
  core/include/webview/detail/platform/darwin/cocoa/literals.hh
  core/include/webview/detail/platform/darwin/objc/Class.hh
  core/include/webview/detail/platform/darwin/objc/autoreleasepool.hh
  core/include/webview/detail/platform/darwin/objc/invoke.hh
  core/include/webview/detail/platform/darwin/objc/literals.hh
  core/include/webview/detail/platform/darwin/objc/memory.hh
  core/include/webview/detail/platform/darwin/objc/objc.hh
  core/include/webview/detail/platform/darwin/webkit/WKOpenPanelParameters.hh
  core/include/webview/detail/platform/darwin/webkit/WKScriptMessage.hh
  core/include/webview/detail/platform/darwin/webkit/WKUserContentController.hh
  core/include/webview/detail/platform/darwin/webkit/WKUserScript.hh
  core/include/webview/detail/platform/darwin/webkit/WKWebView.hh
  core/include/webview/detail/platform/darwin/webkit/WKWebViewConfiguration.hh
  core/include/webview/detail/platform/darwin/webkit/literals.hh
Labels: type: refactor, os: macos

#1286 Sleep before retry try_create_environment for WebView2
  core/include/webview/detail/backends/win32_edge.hh
Labels: type: quality assurance, os: windows

#1288 Remove set_owns_window()
  core/include/webview/detail/backends/cocoa_webkit.hh
  core/include/webview/detail/backends/gtk_webkitgtk.hh
  core/include/webview/detail/backends/win32_edge.hh
  core/include/webview/detail/engine_base.hh
Labels: type: refactor
