Repository webview/webview, pull requests merged in 2025-03, with the labels that each got.

#1258 Amalgamation fixes and tests
  .github/workflows/check.yaml
  README.md
  core/CMakeLists.txt
  core/include/webview/backends.hh
  core/include/webview/c_api_impl.hh
  core/include/webview/detail/backends/cocoa_webkit.hh
  core/include/webview/detail/backends/gtk_webkitgtk.hh
  core/include/webview/detail/backends/win32_edge.hh
  core/include/webview/detail/basic_result.hh
  core/include/webview/detail/engine_base.hh
  core/include/webview/detail/exceptions.hh
  core/include/webview/detail/json.hh
  core/include/webview/detail/native_library.hh
  core/include/webview/detail/optional.hh
  core/include/webview/detail/platform/darwin/cocoa.hh
  core/include/webview/detail/platform/darwin/objc.hh
  core/include/webview/detail/platform/darwin/webkit.hh
  core/include/webview/detail/platform/linux/gtk/compat.hh
  core/include/webview/detail/platform/linux/webkitgtk/compat.hh
  core/include/webview/detail/platform/linux/webkitgtk/dmabuf.hh
  core/include/webview/detail/platform/windows/com_init_wrapper.hh
  core/include/webview/detail/platform/windows/dpi.hh
  core/include/webview/detail/platform/windows/dwmapi.hh
  core/include/webview/detail/platform/windows/iid.hh
  core/include/webview/detail/platform/windows/ntdll.hh
  core/include/webview/detail/platform/windows/reg_key.hh
  core/include/webview/detail/platform/windows/shcore.hh
  core/include/webview/detail/platform/windows/theme.hh
  core/include/webview/detail/platform/windows/user32.hh
  core/include/webview/detail/platform/windows/version.hh
  core/include/webview/detail/platform/windows/webview2/loader.hh
  core/include/webview/detail/user_script.hh
  core/include/webview/detail/utility/string.hh
  core/include/webview/errors.hh
  core/include/webview/json_deprecated.hh
  core/include/webview/types.hh
  core/include/webview/webview.h
  core/src/webview.cc
  scripts/amalgamate/amalgamate.py
  scripts/amalgamate/test/.gitignore
  scripts/amalgamate/test/main.c
  scripts/amalgamate/test/main.cc
  scripts/amalgamate/test/webview.cc
Labels: scope: ci, scope: build, type: fix

#1259 Update Ubuntu GHA runner image from 20.04 to 22.04
  .github/workflows/build_matrix.csv
Labels: scope: ci

#1260 C++11 compatibility for Windows
  README.md
  cmake/modules/FindMSWebView2.cmake
  core/include/webview/detail/platform/windows/com_init_wrapper.hh
  core/include/webview/detail/platform/windows/dpi.hh
  core/include/webview/detail/platform/windows/version.hh
  core/include/webview/detail/platform/windows/webview2/loader.hh
Labels: type: improvement, scope: documentation, scope: ci, scope: build

#1262 Document set_size() behavior difference between GTK 3/4
  core/include/webview/api.h
  core/include/webview/detail/platform/linux/gtk/compat.hh
Labels: scope: documentation

#1265 Temporary run loop refactor
  core/include/webview/detail/backends/cocoa_webkit.hh
  core/include/webview/detail/backends/gtk_webkitgtk.hh
  core/include/webview/detail/backends/win32_edge.hh
  core/include/webview/detail/engine_base.hh
Labels: type: refactor

#1270 Fix window rendering glitch and refactor win32 edge
  core/include/webview/detail/backends/win32_edge.hh
Labels: type: fix

#1275 Adjustments to handling of long-running tests
  core/tests/CMakeLists.txt
  core/tests/src/functional_tests.cc
  core/tests/src/unit_tests.cc
  test_driver/cmake/discovery.cmake
  test_driver/cmake/generate_includes.cmake
Labels: type: improvement, scope: ci, scope: build, os: windows
